### ISSUE TITLE
depth file

### ISSUE THREAD

**Issue by zjw102** [salesforce/ULIP#18]
hello,can you provide depth map file?

**Comment by Tycho-Xue** [comment]
@zjw102, hi, it's already in the provided link for downloading the shapenet55 dataset, for example, all the png files with "_depth0001.png" are the depth mapts.
sfr-ulip-code-release-research/shapenet-55/rendered_images/02691156-10155655850468db78d106ce0a280f87/02691156-10155655850468db78d106ce0a280f87_r_000_depth0001.png
