### ISSUE TITLE
Code for cross-modal retrieval

### ISSUE THREAD

**Issue by Zscozer** [salesforce/ULIP#19]
would you mind sharing your rendering scripts for cross-modal retrieval?

**Comment by Tycho-Xue** [comment]
@Zscozer , sorry for the delay, I will upload it soon.

**Comment by Zscozer** [comment]
> @Zscozer , sorry for the delay, I will upload it soon.
No problem. But I have one more small question: During the training process, is each 3D object randomly paired with only one image, or is each 3D object paired with 60 images (as you mentioned, 30 rendered images and 30 depth maps)?

**Comment by Zscozer** [comment]
Thanks a lot !!!
