### ISSUE TITLE
When will the ULIP-ShapeNet Triplets be released?

### ISSUE THREAD

**Issue by czvvd** [salesforce/ULIP#30]
Thanks for your wonderful work! Currently, I can only find the ULIP-Objaverse Triplets in the provided link. When will the ULIP-ShapeNet Triplets be released?

**Comment by Tycho-Xue** [comment]
@czvvd Thanks for your interest in our work, we should be able to release it next week.

**Comment by czvvd** [comment]
Thanks for your timely reply! Stay following!

**Comment by Tycho-Xue** [comment]
Hi @czvvd , we have uploaded the generated captions for ShapeNet as well, check it out!
