### ISSUE TITLE
Why did you use SLIP (pretrained on YFCC15M), instead of OpenAI CLIP (pretrained 400M image-text pairs)?

### ISSUE THREAD

**Issue by chenguolin** [salesforce/ULIP#31]
Hi, thanks for your wonderful work! I have a question about the pretrained model that you used in the ULIP/ULIP-v2.

According to the ULIP paper, SLIP is adapted because it's an advanced version of CLIP. However, SLIP is pretrained on a much smaller dataset (YFCC15M), while the OpenAI CLIP is trained on 400M image-text pairs. I am curious if you had considered employing the original OpenAI CLIP pretrained on large-scale data for ULIP/ULIP-v2.

Additionally, I notice that the SLIP version located in the initialize_models directory is `slip_base_ep100.pt`. Have you investigated the potential benefits of utilizing larger models?

It is conceivable that CLIP models with a greater number of parameters and pretrained on a more extensive dataset could potentially enhance the performance of ULIP/ULIP-v2.

**Comment by Tycho-Xue** [comment]
Hi @chenguolin, thanks for your interest in our work!
Yeah, we have been thinking about this for a while, it's more about a bandwidth issue right now.
Stay tuned, give us more time, and we might be able to do more experiments on the pre-trained models' side and release it.
