### ISSUE TITLE
Pre-trained model released

### ISSUE THREAD

**Issue by agoodge** [salesforce/ULIP#50]
Hi,

Thank you for the good work.

Could you confirm if the released model checkpoints are pre-trained on ShapeNet or Objaverse?

Thanks!

**Comment by Tycho-Xue** [comment]
Hi @agoodge , only the checkpoint for ULIP-2 is pre-trained on objaverse + shapenet, others are pre-trained only on the shapenet.
thanks

**Comment by agoodge** [comment]
Hi Xue, 

Thank you for your response.

I see in experiments in the paper, ULIP-2 is trained on either ShapeNet **or** Objaverse. Can I confirm that the ULIP-2 checkpoint you released in this repo is pre-trained on both  ShapeNet **and** Objaverse, or just one of them?

**Comment by Tycho-Xue** [comment]
Hi @agoodge, we have a better checkpoint trained on Objaverse+shapenet, which achieved ~85 top1 on modelnet, and ~51 top1 on objaverse-lvis, and it's under the release processing now for ULIP-2, the paper will also be updated soon. the current one i believe is trained on objaverse+shapenet, but the numbers in the paper are accurate if you want to get the numbers for pre-trained on them separately, I can also try to find the separately pre-trained checkpoints to release as well.

**Comment by agoodge** [comment]
Understood. It would be good if you are able to release the separate checkpoints too. Thanks a lot for your answer!

**Comment by Tycho-Xue** [comment]
@agoodge , got it, since it has been a while, let me find the old ones and release them soon. Also, we will release the upgraded ULIP-2 checkpoints very soon, it also includes color this time.
