### ISSUE TITLE
pretrain poinbert

### ISSUE THREAD

**Issue by 944104439** [salesforce/ULIP#52]
when i pretrained pointbert , i got this, how to i solve it ?
Traceback (most recent call last):
  File "main.py", line 545, in <module>
    main(args)
  File "main.py", line 211, in main
    train_stats = train(train_loader, model, criterion, optimizer, scaler, epoch, lr_schedule, args)
  File "main.py", line 299, in train
    outputs = model(*inputs)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/ULIP/models/ULIP_models.py", line 158, in forward
    text_embed = self.encode_text(text_for_one_sample)
  File "/home/ubuntu/ULIP/models/ULIP_models.py", line 115, in encode_text
    x = self.transformer(x)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/ULIP/models/ULIP_models.py", line 70, in forward
    return self.resblocks(x)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/ULIP/models/ULIP_models.py", line 57, in forward
    x = x + self.attention(self.ln_1(x))
  File "/home/ubuntu/ULIP/models/ULIP_models.py", line 54, in attention
    return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0]
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1010, in forward
    attn_mask=attn_mask)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 4988, in multi_head_attention_forward
    q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 4738, in _in_projection_packed
    return linear(q, w, b).chunk(3, dim=-1)
  File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

**Comment by Lazarus0211** [comment]
> when i pretrained pointbert , i got this, how to i solve it ? Traceback (most recent call last): File "main.py", line 545, in main(args) File "main.py", line 211, in main train_stats = train(train_loader, model, criterion, optimizer, scaler, epoch, lr_schedule, args) File "main.py", line 299, in train outputs = model(*inputs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward output = self.module(*inputs[0], **kwargs[0]) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 158, in forward text_embed = self.encode_text(text_for_one_sample) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 115, in encode_text x = self.transformer(x) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 70, in forward return self.resblocks(x) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward input = module(input) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 57, in forward x = x + self.attention(self.ln_1(x)) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 54, in attention return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0] File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1010, in forward attn_mask=attn_mask) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 4988, in multi_head_attention_forward q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 4738, in _in_projection_packed return linear(q, w, b).chunk(3, dim=-1) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear return torch._C._nn.linear(input, weight, bias) RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

Hi, how did you solve this problem?

**Comment by Dali936** [comment]
> > when i pretrained pointbert , i got this, how to i solve it ? Traceback (most recent call last): File "main.py", line 545, in main(args) File "main.py", line 211, in main train_stats = train(train_loader, model, criterion, optimizer, scaler, epoch, lr_schedule, args) File "main.py", line 299, in train outputs = model(*inputs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward output = self.module(*inputs[0], **kwargs[0]) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 158, in forward text_embed = self.encode_text(text_for_one_sample) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 115, in encode_text x = self.transformer(x) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 70, in forward return self.resblocks(x) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward input = module(input) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 57, in forward x = x + self.attention(self.ln_1(x)) File "/home/ubuntu/ULIP/models/ULIP_models.py", line 54, in attention return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0] File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1010, in forward attn_mask=attn_mask) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 4988, in multi_head_attention_forward q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 4738, in _in_projection_packed return linear(q, w, b).chunk(3, dim=-1) File "/home/ubuntu/anaconda3/envs/ulip/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear return torch._C._nn.linear(input, weight, bias) RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
> 
> Hi, how did you solve this problem?

Update your python version to 3.9 and download the corresponding pytorch (it’s been a while i run this code, please contact author if it doesn’t work
