### ISSUE TITLE
Could you share the file "taxonomy.json" in shapenet-55?

### ISSUE THREAD

**Issue by auniquesun** [salesforce/ULIP#54]
Thanks for sharing the paper and code. It's a great work. 

I am wonder the mapping relationship between the taxnomy ids and the class names in shapenet-55 dataset, as the `dataset_3d.py` uses `taxonomy.json`, could you also share it?

https://github.com/salesforce/ULIP/blob/2fed30f12501b0f947ee9e84b5d8620d04545163/data/dataset_3d.py#L304

Thanks.

**Comment by Tycho-Xue** [comment]
@auniquesun it's here
gs://sfr-ulip-code-release-research/shapenet-55/taxonomy.json
also the upgraded ULIP-2 backbone has been uploaded. thanks for the waiting!

**Comment by auniquesun** [comment]
@Tycho-Xue  Thanks for you reply.
