### ISSUE TITLE
Problem when loading pointbert_ULIP-2.pt pretrained model

### ISSUE THREAD

**Issue by iLori-Jiang** [salesforce/ULIP#60]
@Tycho-Xue

When loading this pretrained model 'pointbert_ULIP-2.pt' in 'main.py' by the script 'test_ulip2_pointbert_modelnet40.sh'

inside 'test_zeroshot_3d_ulip2()' function:

    model = getattr(models, args.model)(args=args)

    model.cuda()

    -> model.load_state_dict(state_dict, strict=False)

    print("=> loaded pretrained checkpoint '{}'".format(args.test_ckpt_addr))

Meet the following problem:

RuntimeError: Error(s) in loading state_dict for ULIP2_WITH_OPENCLIP:
	size mismatch for pc_projection: copying a param with shape torch.Size([768, 512]) from checkpoint, the shape in current model is torch.Size([768, 1280]).
	size mismatch for point_encoder.encoder.first_conv.0.weight: copying a param with shape torch.Size([128, 3, 1]) from checkpoint, the shape in current model is torch.Size([128, 6, 1]).

Why the size is not matching?

**Comment by iLori-Jiang** [comment]
Besides, I find the size in ULIP_models.py:

self.pc_projection = nn.Parameter(torch.empty(kwargs.pc_feat_dims, 1280))

at line 191 of the init of the ULIP2_WITH_OPENCLIP class. Why you define it to be 1280, but in the pretrained model it is just 512?

**Comment by iLori-Jiang** [comment]
And then, I find in the 'models/pointbert/point_encoder.py'

    self.encoder = Encoder(encoder_channel=self.encoder_dims, input_dim=6)

at line 256 inside the init of PointTransformer_Colored class. You define the input_dim=6, where the default of this Encoder is 3 and match your pretrained model. Why here you change it from 3 to 6?

**Comment by iLori-Jiang** [comment]
UPDATE:

Found the solution that actually this is the correct final model:

https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt

Successfully loaded the model and do the inference.

Just wish there could be more descriptions about the cloud files so that we can know which to use

**Comment by atomishcv** [comment]
i also run the  'test_ulip2_pointbert_modelnet40.sh'. But i download the 'ulip2_pointbert_colored' model from the huggingface is too slow!!, do you have any suggestions?

**Comment by iLori-Jiang** [comment]
@atomishcv Hi I didn't know there is models on Huggingface, I only downloaded them from the Google cloud storage, which is the link above. The download speed is fast, you can try that

**Comment by atomishcv** [comment]
thank for your advice!

**Comment by Lazarus0211** [comment]
> UPDATE:
> 
> Found the solution that actually this is the correct final model:
> 
> https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt
> 
> Successfully loaded the model and do the inference.
> 
> Just wish there could be more descriptions about the cloud files so that we can know which to use

Hi，I would like to know if you have pretrain ULIP2_PointBert_colored model?

**Comment by labixiaochao** [comment]
> UPDATE:
> 
> Found the solution that actually this is the correct final model:
> 
> https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt
> 
> Successfully loaded the model and do the inference.
> 
> Just wish there could be more descriptions about the cloud files so that we can know which to use

data/modelnet40_normal_resampled/modelnet40_colored_10k_pc.npyDo you know where this file is in this data set

**Comment by labixiaochao** [comment]
> > 更新： 
> > 找到的解决方案实际上是正确的最终模型： 
> > [https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt ](https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt)
> > 已成功加载模型并执行推理。 
> > 只是希望能有更多关于云文件的描述，以便我们知道该使用哪个
> 
> 嗨，我想知道您是否有预训练ULIP2_PointBert_colored模型？

Did your code run smoothly? Did you encounter this problem: IndexError: index 9630 is out of bounds for axis 0 with size 8192

**Comment by labixiaochao** [comment]
> 更新：
> 
> 找到的解决方案实际上是正确的最终模型：
> 
> [https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt ](https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt)
> 
> 已成功加载模型并执行推理。
> 
> 只是希望能有更多关于云文件的描述，以便我们知道该使用哪个

of bounds for axis 0 with size 8192 error, I think it is because my dataset only contains 8192 points instead of 10000 points

**Comment by labixiaochao** [comment]
> 更新：
> 
> 找到的解决方案实际上是正确的最终模型：
> 
> [https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt ](https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt)
> 
> 已成功加载模型并执行推理。
> 
> 只是希望能有更多关于云文件的描述，以便我们知道该使用哪个

Do you have a link to your dataset? The error of bounds for axis 0 with size 8192 is because my dataset only contains 8192 points instead of 10000 points.

**Comment by URRealHero** [comment]
> UPDATE:
> 
> Found the solution that actually this is the correct final model:
> 
> https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt
> 
> Successfully loaded the model and do the inference.
> 
> Just wish there could be more descriptions about the cloud files so that we can know which to use

I still got this problem after downloading `https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt`. Still

```shell
Traceback (most recent call last):
  File "encode_features.py", line 73, in <module>
    main()
  File "encode_features.py", line 64, in main
    model = load_model(args)
  File "encode_features.py", line 33, in load_model
    model.load_state_dict(state_dict, strict=False)
  File "/root/anaconda3/envs/ulip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ULIP_WITH_IMAGE:
        size mismatch for pc_projection: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 512]).
        size mismatch for point_encoder.encoder.first_conv.0.weight: copying a param with shape torch.Size([128, 6, 1]) from checkpoint, the shape in current model is torch.Size([128, 3, 1]).
```

May I modify the dimension in the model?
or how did you fix it.

Appreciate it.

**Comment by URRealHero** [comment]
> UPDATE:
> 
> Found the solution that actually this is the correct final model:
> 
> https://storage.googleapis.com/sfr-ulip-code-release-research/ULIP-2/models/ULIP-2-PointBERT-10k-colored-pc-pretrained.pt
> 
> Successfully loaded the model and do the inference.
> 
> Just wish there could be more descriptions about the cloud files so that we can know which to use

sry, found the error cuz using the wrong model ULIP_WITH_IMAGE, instead ULIP2_WITH_OPENCLIP should be applied

**Comment by Tycho-Xue** [comment]
Yeah, so for the open clip version the dim is different👍
