### ISSUE TITLE
What is the total size of the floder shapenet-55 

### ISSUE THREAD

**Issue by adsf0427** [salesforce/ULIP#7]
I try to download the data from the google cloud, it consumed more than 900G datastorage.

**Comment by Tycho-Xue** [comment]
Hi, I think the most part of it is the rendered images, for each object I rendered with 30 angles and each angle has 5 types of renderings, so around 52.5k * 150 images. I uploaded the whole rendering in case someone wants it. in the paper I mentioned I only used two rendering types, which are RGB images and depth maps.

**Comment by adsf0427** [comment]
Thank you. I wonder if u can make an archive of the datasets in the future, thanks again.

**Comment by Tycho-Xue** [comment]
Do you mean to compress them into a single file? Yeah I can do that in the future

**Comment by Bohuaw** [comment]
Could you please upload a version of the RGB and depth render data used in this paper? The amount of data in this full version is too much. Thank you!

**Comment by Tycho-Xue** [comment]
@Bohuaw I can try to do that, also, maybe there is command which contains regex to do for downloading that as well

**Comment by zzzzaoqi** [comment]
@Tycho-Xue Where can I download the data used in this paper?  thank u !

**Comment by zzzzaoqi** [comment]
@Tycho-Xue Sorry, maybe I wasn't very clear, what I meant was the version of RGB and deep rendered data used in this paper. The full version has too much data. Thank you!

**Comment by Tycho-Xue** [comment]
@zzzzaoqi, got it, I'll try to find some time to do that, I'm actually out of office recently. Meanwhile, please kindly search if there is a way to do regex while downloading.

**Comment by auniquesun** [comment]
> @zzzzaoqi, got it, I'll try to find some time to do that, I'm actually out of office recently. Meanwhile, please kindly search if there is a way to do regex while downloading.

can you provide a regex example for downloading? maybe I can solve the problem.

**Comment by Tycho-Xue** [comment]
@auniquesun @zzzzaoqi, so for every 3d model and render angle, the rendered images contain [.png, _albedo0001.png, _depth0001.png, _id0001.png, _normal0001.png] five images in total, in ULIP, we currently experimented with .png and _depth0001.png and only used these two types of image, we uploaded all to facilitate the research in case somebody else wants to explore to use other types of images.
Not sure if GCP has the regex feature to control to only download the images with .png and _depth0001.png, feel free to try if you figured out how to download a part of the dataset using things like regex.

**Comment by Tycho-Xue** [comment]
@adsf0427, @Bohuaw, @zzzzaoqi, @auniquesun, I've uploaded a "only_rgb_depth_images" folder, which is around 420GB, it contains all the images I used for the pre-training, which is much smaller than the previous full image folder.
Also, checkout our ULIP-2 paper, where we released "ULIP-Objaverse Triplets" and "ULIP-ShapeNet Triplets"!

**Comment by 944104439** [comment]
If I want to replicate this study, do I just need to download the data in shapenet-55?
![image](https://github.com/salesforce/ULIP/assets/83868746/c2f1b8fa-1d16-4b4f-b08f-05fe5c5adf04)

**Comment by Tycho-Xue** [comment]
hi @944104439 , yes, I think what you selected is a good start for pre-training on shapenet.
