### ISSUE TITLE
Cannot download files from cloud storage...

### ISSUE THREAD

**Issue by LANYAN1212** [salesforce/ULIP#8]
Thank you very much for the impressive work! However, I cannot download files from google cloud storage since I am from China and I cannot register google account. Could you please upload files in some other ways, such as google drive?
Thank you very much for your attention!

**Comment by Tycho-Xue** [comment]
@LANYAN1212 Thanks for your interest in our work! Since I'm using the default data-sharing platform by my company, I have to check with our ops team to see if there is any other way to share the data. Maybe you can try with VPN?

**Comment by LANYAN1212** [comment]
Yes, I would have a try. By the way, could you also release the zero-shot classification code on Scanobjectnn dataset? Thanks a lot!

**Comment by Tycho-Xue** [comment]
@LANYAN1212 I will try to find some bandwidth to do that
